// Copyright (c) 2026 Databricks, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Loader for the SEA (Statement Execution API) native binding.
 *
 * Round 1b: minimal pass-through to the napi-rs auto-generated
 * `index.js` shim in `native/sea/`. The shim itself picks the right
 * per-platform `.node` artifact (linux-x64-gnu today; more triples in
 * the bundling feature).
 *
 * Round 2+ will extend this with: lazy require to defer the `.node`
 * load until the first SEA call, structured load-error diagnostics
 * (which platform/arch was attempted, whether the package was
 * installed at all), and a JS-side `DBSQLLogger` install path that
 * forwards to the binding's `installLogger()` once that surface lands.
 */

import type { SeaNativeConnectionOptions } from './SeaAuth';

// The path is relative to this file at runtime (`dist/sea/SeaNativeLoader.js`)
// resolving to `dist/sea/../../native/sea/index.js` once `tsc` has emitted
// to `dist/`. We use a require-time path resolution because the napi
// shim is plain CommonJS and not part of the TS source tree.
//
// eslint-disable-next-line @typescript-eslint/no-var-requires, import/no-dynamic-require, global-require
const native = require('../../native/sea/index.js');

/**
 * JS-visible per-execute options carried over the napi binding boundary.
 * Mirrors the `ExecuteOptions` shape generated by napi-rs into
 * `native/sea/index.d.ts`. Re-declared here so the JS adapter layer
 * isn't tied to the binding-generated types.
 */
export interface SeaExecuteOptions {
  initialCatalog?: string;
  initialSchema?: string;
  sessionConfig?: Record<string, string>;
}

/**
 * Arrow IPC payload returned by `Statement.fetchNextBatch()`. Carries a
 * complete Arrow IPC stream (schema header + 1 record-batch message).
 */
export interface SeaArrowBatch {
  ipcBytes: Buffer;
}

/**
 * Arrow IPC payload returned by `Statement.schema()` (schema header only).
 */
export interface SeaArrowSchema {
  ipcBytes: Buffer;
}

/**
 * Typed surface for the opaque napi `Statement` handle. Method signatures
 * match `native/sea/index.d.ts` exactly so the JS-side wrappers can
 * `await` them without `any` casts.
 */
export interface SeaNativeStatement {
  fetchNextBatch(): Promise<SeaArrowBatch | null>;
  schema(): Promise<SeaArrowSchema>;
  cancel(): Promise<void>;
  close(): Promise<void>;
}

/**
 * Raw `getInfo` return value from the napi binding. The kernel packs a
 * single variant field — only one of the optional properties will be
 * set. Mirrors the subset of `TGetInfoValue` that the SEA path can
 * synthesise from server responses.
 *
 * Shape is a best-guess pending `metadata-rust-impl` finalising the
 * `Connection.getInfo` napi signature. Reconcile against
 * `native/sea/index.d.ts` once their commit lands.
 */
export interface SeaNativeInfoValue {
  stringValue?: string;
  smallIntValue?: number;
  integerBitmask?: number;
  integerFlag?: number;
}

/**
 * Typed surface for the opaque napi `Connection` handle.
 *
 * The 9 metadata-returning methods below (`listCatalogs`, `listSchemas`,
 * etc.) are added by `metadata-rust-impl` on the
 * `msrathore/krn-napi-metadata-exposure` branch. Signatures here are
 * derived from the pyo3 parallel (`napi-binding/pyo3/src/metadata.rs`)
 * and the kernel `Metadata` API (`src/metadata_v0.rs`). Reconcile
 * against the generated `native/sea/index.d.ts` when that commit lands.
 */
export interface SeaNativeConnection {
  executeStatement(sql: string, options: SeaExecuteOptions): Promise<SeaNativeStatement>;

  // ── Metadata methods ──────────────────────────────────────────────────
  /** All catalogs visible to the session. */
  listCatalogs(): Promise<SeaNativeStatement>;

  /** Schemas filtered by catalog (exact) and schema name LIKE pattern. */
  listSchemas(catalog: string | undefined, schemaPattern: string | undefined): Promise<SeaNativeStatement>;

  /** Tables filtered by catalog (exact), schema and table LIKE patterns, and optional type list. */
  listTables(
    catalog: string | undefined,
    schemaPattern: string | undefined,
    tablePattern: string | undefined,
    tableTypes: string[] | undefined,
  ): Promise<SeaNativeStatement>;

  /** Columns filtered by catalog (exact), schema/table/column LIKE patterns. */
  listColumns(
    catalog: string | undefined,
    schemaPattern: string | undefined,
    tablePattern: string | undefined,
    columnPattern: string | undefined,
  ): Promise<SeaNativeStatement>;

  /** Functions filtered by catalog (exact), schema and name LIKE patterns. */
  listFunctions(
    catalog: string | undefined,
    schemaPattern: string | undefined,
    functionPattern: string | undefined,
  ): Promise<SeaNativeStatement>;

  /** All supported table types. No wire call — static result. */
  listTableTypes(): Promise<SeaNativeStatement>;

  /** All supported SQL data types. No wire call — static result. */
  listTypeInfo(): Promise<SeaNativeStatement>;

  /**
   * Primary keys for the given table. Catalog and schema are optional;
   * the kernel requires them to be non-empty strings if supplied.
   */
  getPrimaryKeys(
    catalog: string | undefined,
    schema: string | undefined,
    table: string,
  ): Promise<SeaNativeStatement>;

  /**
   * Foreign-key relationships (getCrossReference in JDBC terms). Foreign
   * side is required; parent side is optional.
   */
  getCrossReference(
    parentCatalog: string | undefined,
    parentSchema: string | undefined,
    parentTable: string | undefined,
    foreignCatalog: string,
    foreignSchema: string,
    foreignTable: string,
  ): Promise<SeaNativeStatement>;

  /**
   * General server info for the given info type. Returns a raw value
   * object; the JS adapter wraps it in `InfoValue`.
   */
  getInfo(infoType: number): Promise<SeaNativeInfoValue>;

  close(): Promise<void>;
}

/**
 * Public surface of the native binding exposed to the rest of the
 * NodeJS driver. Round 2 lands `openSession` + opaque `Connection` /
 * `Statement` classes (the binding-generated `.d.ts` is the source of
 * truth for their method signatures — see `native/sea/index.d.ts`).
 */
export interface SeaNativeBinding {
  /** Returns the native crate version (smoke test for the binding's load path). */
  version(): string;
  /**
   * Open a session over PAT, OAuth M2M, or OAuth U2M auth. Returns an
   * opaque Connection. The discriminated `SeaNativeConnectionOptions`
   * union from `SeaAuth` is the source of truth for the per-mode
   * required fields, so the loader-seam enforces the same compile-time
   * check the adapter applies — a caller can't bypass
   * `buildSeaConnectionOptions` and pass, say, `{ authMode: 'Pat' }`
   * with no token.
   */
  openSession(opts: SeaNativeConnectionOptions): Promise<SeaNativeConnection>;
  /** Opaque Connection class — instance methods on the binding-generated d.ts. */
  Connection: Function;
  /** Opaque Statement class — instance methods on the binding-generated d.ts. */
  Statement: Function;
}

/**
 * Returns the loaded native binding. Throws if the platform-specific
 * `.node` artifact cannot be found (napi-rs's auto-generated shim
 * surfaces a descriptive error in that case).
 */
export function getSeaNative(): SeaNativeBinding {
  return native as SeaNativeBinding;
}

/**
 * Convenience accessor for the smoke-test path. Equivalent to
 * `getSeaNative().version()` but reads more naturally in tests and
 * REPLs.
 */
export function version(): string {
  return getSeaNative().version();
}
