/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * JS-visible connection options. Empty in Round 1b; Round 2 may add
 * per-connection scope fields (catalog, schema, session config map).
 */
export interface ConnectionOptions {
  
}
/**
 * JS-visible constructor options. Round 2 will populate this with
 * real fields (host, warehouseId, auth, …); for the scaffold it is
 * intentionally empty so the JS smoke test can call `new Database({})`
 * without TypeScript complaining about unknown properties.
 */
export interface DatabaseOptions {
  /**
   * Workspace host URL (e.g. `https://workspace.databricks.com`).
   * Optional in Round 1b; Round 2 makes it required.
   */
  host?: string
  /** Warehouse id. Optional in Round 1b; Round 2 makes it required. */
  warehouseId?: string
}
/**
 * Returns the native binding's crate version (`CARGO_PKG_VERSION`).
 *
 * Acts as the round-1b smoke test: a JS `require()` of the `.node`
 * artifact that successfully calls `version()` proves the binding's
 * build + load + dispatch path is wired correctly.
 */
export declare function version(): string
/** Opaque connection handle. Round 1b: marker only; no kernel state. */
export declare class Connection {
  /**
   * Construct a new connection handle. Round 1b is a no-op shell;
   * Round 2 will wire it to `Database`'s `Session` (likely via an
   * async `Database::connect()` factory rather than a JS-side
   * `new Connection()`).
   */
  constructor(options: ConnectionOptions)
}
/**
 * Opaque database handle on the JS side.
 *
 * Holds `Option<Session>` so `close()` (Round 2) can `.take()` the
 * session out and `.await` an async close, leaving `inner = None`.
 * The `Drop` impl checks `inner` to decide whether to schedule a
 * fire-and-forget close on the captured tokio runtime.
 */
export declare class Database {
  /**
   * Construct a new database handle. Round 1b: the options are
   * stashed for diagnostic purposes only — no network call.
   */
  constructor(options: DatabaseOptions)
}
