/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Per-statement options for `Connection.executeStatement`.
 *
 * Mirrors the kernel `StatementSpec` knobs that are safe to thread
 * through napi without a kernel-side change. Today this covers:
 * - `statementConf` — per-statement Spark conf overlay
 *   (`StatementSpec.statement_conf` → SEA `parameters` /
 *   Thrift `confOverlay`)
 * - `queryTags` — convenience wrapper over `statementConf` with
 *   key `query_tags`; serialised to the same comma-separated
 *   `key:value` wire shape NodeJS Thrift's `serializeQueryTags`
 *   produces (`lib/utils/queryTags.ts`). Backslashes in keys are
 *   doubled; backslash/colon/comma in values are backslash-escaped.
 *
 * `rowLimit` (SEA `row_limit`) and `queryTimeoutSecs` (the per-statement
 * server wait timeout) are exposed here and threaded onto the kernel
 * `StatementSpec`. Positional and named parameters remain deferred: they
 * require a non-trivial JS↔napi `TypedValue` mapping and land in a
 * follow-on PR.
 *
 * **Tag-order caveat (M4 parity note).** The napi `queryTags` field
 * is a Rust `HashMap<String, String>` whose iteration order is
 * non-deterministic, so the serialised `query_tags` value may have
 * a different key order than Thrift's `serializeQueryTags` (which
 * iterates `Object.keys(...)` in insertion order) for the same
 * input. The SEA server is order-insensitive on conf values, so
 * the two are functionally equivalent. If a caller needs
 * byte-identical Thrift parity, the JS adapter pre-serialises via
 * `serializeQueryTags` and writes the result into
 * `statementConf["query_tags"]` directly — see
 * `SeaSessionBackend.executeStatement` in the NodeJS driver. This
 * path is the one the production code uses.
 */
export interface ExecuteOptions {
  /**
   * Per-statement Spark conf overlay. Merged on top of the
   * session-level `sessionConf` at execute time; this map wins
   * on key collisions. Unknown keys are rejected by the server.
   */
  statementConf?: Record<string, string>
  /**
   * Query tags as key→value pairs. Serialised to a comma-
   * separated `key:value` string (backslash-escaping `\`, `:`,
   * `,`) and placed into `statementConf["query_tags"]`, matching
   * NodeJS Thrift's `serializeQueryTags` wire shape. Passing
   * both `queryTags` AND a `query_tags` key in `statementConf`
   * raises `InvalidArgument` — the caller's intent is ambiguous
   * so we refuse to silently pick one over the other.
   *
   * See the struct-level "Tag-order caveat" for the
   * HashMap-iteration-order vs `Object.keys`-iteration-order
   * divergence and the byte-identical-Thrift-parity workaround.
   */
  queryTags?: Record<string, string>
  /**
   * Server-side cap on the number of rows this statement returns
   * (SEA `row_limit`), independent of any SQL `LIMIT`. Maps to
   * `StatementSpec.row_limit`. Omitted ⇒ no driver-imposed cap.
   */
  rowLimit?: number
  /**
   * Per-statement server wait timeout in whole seconds. Bounds how
   * long the server waits before cancelling the statement
   * (`on_wait_timeout = CANCEL`), surfacing as a timeout — the
   * server statement timeout (JDBC `setQueryTimeout`). Maps to
   * `StatementSpec.query_timeout_secs`. Distinct from the
   * connection-level transport timeout. The SEA wire caps it at 50s.
   */
  queryTimeoutSecs?: number
}
/**
 * Authentication mode selector crossing the napi boundary. The string
 * literals are what napi-rs emits from this `#[napi(string_enum)]` — the
 * NodeJS SEA adapter (`SeaAuth`) matches them verbatim (`'Pat'`,
 * `'OAuthM2m'`, `'OAuthU2m'`).
 *
 * Mirrors the kernel [`AuthConfig`] variants this binding supports.
 * `OAuthFederation` / `External` are intentionally not exposed yet — the
 * kernel marks federation as not-yet-implemented and `External` is a
 * Rust-trait escape hatch with no JS-callback bridge.
 */
export const enum AuthMode {
  /** Personal access token (`token`). */
  Pat = 'Pat',
  /** OAuth 2.0 machine-to-machine — `oauthClientId` + `oauthClientSecret`. */
  OAuthM2m = 'OAuthM2m',
  /**
   * OAuth 2.0 user-to-machine (browser flow) — optional `oauthClientId`
   * + `oauthRedirectPort`.
   */
  OAuthU2m = 'OAuthU2m'
}
/**
 * JS-visible options for opening a Databricks SQL session.
 *
 * Authentication is selected by `authMode` (default [`AuthMode::Pat`]):
 * - `Pat` — `token` required.
 * - `OAuthM2m` — `oauthClientId` + `oauthClientSecret` required.
 * - `OAuthU2m` — `oauthClientId` / `oauthRedirectPort` optional (kernel
 *   defaults to the `databricks-cli` client on port 8020).
 *
 * Catalog / schema / sessionConf are applied once at session creation
 * and remain in effect for every statement run on the resulting
 * `Connection`. The SEA wire protocol carries them on
 * `CreateSession`, not on `ExecuteStatement` — so there is no
 * per-statement override path on this binding.
 */
export interface ConnectionOptions {
  /**
   * Workspace host, e.g. `adb-…azuredatabricks.net`. The kernel
   * normalises this — bare hostnames get `https://` prepended.
   */
  hostName: string
  /**
   * JDBC-style HTTP path, e.g. `/sql/1.0/warehouses/abc123`. The
   * kernel parses out the warehouse id.
   */
  httpPath: string
  /**
   * Authentication mode. Omitted ⇒ [`AuthMode::Pat`] (back-compat:
   * existing PAT callers pass only `token`).
   */
  authMode?: AuthMode
  /**
   * Personal access token. Required (and non-empty) for
   * [`AuthMode::Pat`]; ignored otherwise.
   */
  token?: string
  /**
   * OAuth client id. Required for [`AuthMode::OAuthM2m`]; optional for
   * [`AuthMode::OAuthU2m`] (kernel defaults to `databricks-cli`).
   */
  oauthClientId?: string
  /** OAuth client secret. Required for [`AuthMode::OAuthM2m`]. */
  oauthClientSecret?: string
  /**
   * Localhost callback port for the [`AuthMode::OAuthU2m`] browser
   * flow. Omitted ⇒ kernel default (8020).
   */
  oauthRedirectPort?: number
  /**
   * OAuth scopes override (M2M / U2M). Omitted ⇒ kernel defaults
   * (`["all-apis"]` for M2M; `["all-apis", "offline_access"]` for U2M).
   */
  oauthScopes?: Array<string>
  /**
   * Default catalog for statements executed on this session.
   * Routed through the kernel's `DefaultOpts` and onto the SEA
   * `CreateSession.catalog` wire field.
   */
  catalog?: string
  /**
   * Default schema for statements executed on this session.
   * Routed through the kernel's `DefaultOpts` and onto the SEA
   * `CreateSession.schema` wire field.
   */
  schema?: string
  /**
   * Server-bound session conf (Spark conf, `ANSI_MODE`, `TIMEZONE`,
   * query-tag presets, …). Forwarded verbatim to SEA
   * `session_confs`. Unknown keys are rejected server-side.
   */
  sessionConf?: Record<string, string>
  /**
   * Maximum number of pooled HTTP connections per host. Routes
   * through the kernel's [`HttpConfig::pool_max_idle_per_host`].
   * Tunes the underlying `reqwest` connection pool — higher values
   * reduce reconnect overhead when many statements run
   * concurrently against the same warehouse.
   *
   * When the JS caller does NOT provide `maxConnections`, the napi
   * binding applies a NodeJS-driver-appropriate default of
   * [`NAPI_DEFAULT_POOL_MAX_IDLE_PER_HOST`] (100) — chosen to match
   * the JDBC driver's `HttpConnectionPoolSize` default and to close
   * the throughput gap vs the NodeJS Thrift driver's
   * `maxSockets: Infinity` pool for bursty workloads. The kernel
   * core's [`HttpConfig::pool_max_idle_per_host`] default remains
   * at the conservative kernel value (10); each binding chooses
   * its own user-facing default. Mirrors the Python connector's
   * `max_connections` kwarg on the SEA backend, which exposes the
   * knob but keeps its own urllib3-aligned default of 10.
   *
   * Napi-rs serialises `u32` as JS `number`; values up to
   * `2^32 - 1` round-trip safely (any reasonable pool size fits).
   */
  maxConnections?: number
}
/**
 * Open a Databricks SQL session and return an opaque `Connection`
 * wrapping the kernel `Session`. Authentication is selected by
 * `options.auth_mode` (PAT / OAuth M2M / OAuth U2M) — see
 * [`build_auth_config`].
 *
 * The JS-visible name is `openSession` (napi-rs converts snake_case
 * to camelCase for free functions).
 */
export declare function openSession(options: ConnectionOptions): Promise<Connection>
/**
 * A single Arrow IPC stream payload encoding one record batch (plus
 * the schema header so the JS-side reader is stateless).
 */
export interface ArrowBatch {
  /**
   * Arrow IPC stream payload (schema header + 1 record-batch
   * message). Decode with `apache-arrow`'s `RecordBatchReader`.
   */
  ipcBytes: Buffer
}
/**
 * An Arrow IPC stream payload encoding just the result schema (no
 * record-batch messages). Returned by `Statement.schema()`.
 */
export interface ArrowSchema {
  /**
   * Arrow IPC stream payload (schema header only, no record-batch
   * messages). Decode with `apache-arrow`'s `RecordBatchReader` —
   * the reader will expose the schema and immediately end.
   */
  ipcBytes: Buffer
}
/**
 * Returns the native binding's crate version (`CARGO_PKG_VERSION`).
 *
 * Originally the round-1b smoke test; kept as a cheap "is the binding
 * loaded?" probe for the JS-side loader's structured diagnostics.
 */
export declare function version(): string
/**
 * Opaque connection handle wrapping a kernel `Session`.
 *
 * `inner` is `Arc<Mutex<Option<Session>>>` so:
 * - the Drop impl can clone the `Arc` and `.take()` the session on a
 *   background tokio task without holding `&mut self` (which Drop is
 *   forbidden from doing across an `await`),
 * - `close()` can `.take()` the session to consume it for the kernel's
 *   move-by-value `Session::close(self)` signature.
 *
 * **Current concurrency shape** — `executeStatement` holds
 * `inner.lock()` across `stmt.execute().await`, so two concurrent
 * `Promise.all([executeStatement(q1), executeStatement(q2)])` calls
 * on the same Connection serialise even though the kernel transport
 * supports concurrent statements per session, and `close()` blocks
 * behind any in-flight execute. The kernel's `Session::statement()`
 * is `&self`-callable, so the right shape is `Arc<Session>` with
 * concurrent execute paths; that lands in the follow-up lock-shape
 * refactor — see
 * `sea-workflow/jira-candidates/2026-05-24-napi-cancel-during-fetch.md`.
 */
export declare class Connection {
  /**
   * Server-issued session id. Cached at construction; readable
   * even after `close()` so JS-side log lines can correlate
   * against kernel / server logs which key on the same id.
   */
  get sessionId(): string
  /**
   * Execute a SQL statement and return a Statement handle that
   * streams batches via `fetchNextBatch()`.
   *
   * Catalog / schema / sessionConf are session-level
   * (`openSession`). Per-statement options on `ExecuteOptions`:
   * - `statementConf` — per-statement Spark conf overlay
   * - `queryTags` — serialised to a comma-separated `key:value`
   *   string and placed in `statement_conf["query_tags"]`,
   *   matching NodeJS Thrift's `serializeQueryTags` wire shape
   *
   * `options` is omitted/`None` for the no-options path; passing
   * `{ statementConf: {} }` (an empty map) is treated the same as
   * omission to keep the wire shape stable for the common case.
   */
  executeStatement(sql: string, options?: ExecuteOptions | undefined | null): Promise<Statement>
  /**
   * Explicit close. Awaits the server-side `DeleteSession` so the
   * JS caller can observe failures (auth revoked mid-session,
   * warehouse stopped, network error). Idempotent — a second call
   * on an already-closed connection returns `Ok`.
   *
   * **Errors are terminal from the JS side.** The kernel session
   * handle is consumed (`take()`) BEFORE the wire `DeleteSession`
   * runs, because `Session::close` takes `self` by value. On `Err`,
   * the napi `inner` is already `None`, so a JS-side retry sees a
   * closed connection and returns `Ok(())` without re-attempting
   * the wire call. The kernel's own `Drop` fire-and-forget retry
   * runs once in the background — the JS caller can log the error
   * but cannot drive a retry. If you need retry-on-failure
   * semantics for `DeleteSession`, layer them above this method.
   */
  close(): Promise<void>
}
/**
 * Opaque executed-statement handle.
 *
 * **Current concurrency shape** — every method takes `inner.lock()`
 * and holds the guard across the kernel `.await`. tokio `Mutex` is
 * FIFO, so cancel/close queue behind any in-flight `fetchNextBatch`
 * until it returns naturally. This is a known limitation that exists
 * because the napi shape has not yet been split into an
 * `Arc<dyn ExecutedStatementHandle>` (for cancel/close, which the
 * kernel exposes as `&self`-callable) plus a `Mutex<Option<…>>` only
 * for the borrowed-mut fetch path. The lock-shape refactor needs a
 * small kernel-side accessor and lands in a follow-up PR — see
 * `sea-workflow/jira-candidates/2026-05-24-napi-cancel-during-fetch.md`.
 *
 * `schema` and `statement_id` are cached at construction so they
 * survive `close()` — JS callers building error reports against a
 * disposed statement can still read them.
 */
export declare class Statement {
  /**
   * Server-issued statement id. Cached at construction; readable
   * even after `close()` so JS-side log lines can correlate against
   * kernel / server logs which key on the same id.
   */
  get statementId(): string
  /**
   * Pull the next batch of results. Returns `null` when the stream
   * is exhausted. The returned `ArrowBatch.ipcBytes` is a complete
   * Arrow IPC stream (schema header + 1 record-batch message)
   * suitable for handing to `apache-arrow`'s `RecordBatchReader`.
   *
   * On `Err`, the stream is in an unspecified state — call
   * `close()` and discard the `Statement`. Subsequent
   * `fetchNextBatch()` calls after an error are not guaranteed to
   * succeed or fail consistently.
   */
  fetchNextBatch(): Promise<ArrowBatch | null>
  /**
   * Result schema as an Arrow IPC payload (schema header only, no
   * record-batch message). Available before any batches have been
   * fetched, and remains available after `close()` — the kernel
   * materialises the schema eagerly so JS callers can build error
   * reports against a disposed statement.
   *
   * Sync because the body has no `.await` — `encode_ipc_stream` is
   * pure CPU work over an `Arc<Schema>` already cached on the
   * wrapper. Mirrors `pyo3/src/statement.rs::arrow_schema` (sync).
   * napi-rs converts a panic in a sync `#[napi]` entry point into a
   * thrown JS error via its own macro-expanded boundary, so the
   * `util::guarded` `catch_unwind` wrapper that the `async fn`
   * entry points use is not required for this method.
   */
  schema(): ArrowSchema
  /**
   * Server-side cancel.
   *
   * Short-circuits to `Ok(())` if `fetchNextBatch` has already
   * returned `null` (stream naturally exhausted) — matches the
   * JDBC `Statement.cancel()` no-op-after-completion contract, so
   * JS callers can fire cancel defensively without distinguishing
   * "real cancel" from "raced with natural completion."
   *
   * Returns `KernelError(InvalidStatementHandle)` if the statement
   * has been explicitly `close()`d.
   */
  cancel(): Promise<void>
  /**
   * Explicit close. Awaits the server-side `CloseStatement` so the
   * JS caller can observe failures (auth revoked mid-session,
   * network error, server-side error). Idempotent — a second call
   * on an already-closed statement returns `Ok`.
   *
   * **Errors are terminal from the JS side.** The kernel executed
   * handle is taken out of `inner` BEFORE the wire `CloseStatement`
   * runs (so `Drop` knows there's nothing left to clean up). On
   * `Err`, the napi `inner` is already `None`, so a JS-side retry
   * sees a closed statement and returns `Ok(())` without re-
   * attempting the wire call. The kernel-level `ExecutedStatement`
   * has been consumed at that point and the value is dropped on
   * the way out of the closure — the kernel's `ExecutedStatement::
   * Drop` then fires-and-forgets a single retry on the captured
   * runtime. The JS caller can log the error but cannot drive a
   * further retry. If you need retry-on-failure semantics for
   * `CloseStatement`, layer them above this method.
   */
  close(): Promise<void>
}
