/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * JS-visible options for opening a Databricks SQL session over PAT.
 *
 * M0 supports PAT only — `token` is required. OAuth M2M / U2M variants
 * land in M1 along with a discriminated-union shape on the JS side.
 *
 * Catalog / schema / sessionConf are applied once at session creation
 * and remain in effect for every statement run on the resulting
 * `Connection`. The SEA wire protocol carries them on
 * `CreateSession`, not on `ExecuteStatement` — so there is no
 * per-statement override path in either this binding or pyo3.
 */
export interface ConnectionOptions {
  /**
   * Workspace host, e.g. `adb-…azuredatabricks.net`. The kernel
   * normalises this — bare hostnames get `https://` prepended.
   */
  hostName: string
  /**
   * JDBC-style HTTP path, e.g. `/sql/1.0/warehouses/abc123`. The
   * kernel parses out the warehouse id.
   */
  httpPath: string
  /**
   * Personal access token. Must be non-empty (the kernel rejects
   * empty PATs at session construction).
   */
  token: string
  /**
   * Default catalog for statements executed on this session.
   * Routed through the kernel's `DefaultOpts` and onto the SEA
   * `CreateSession.catalog` wire field.
   */
  catalog?: string
  /**
   * Default schema for statements executed on this session.
   * Routed through the kernel's `DefaultOpts` and onto the SEA
   * `CreateSession.schema` wire field.
   */
  schema?: string
  /**
   * Server-bound session conf (Spark conf, `ANSI_MODE`, `TIMEZONE`,
   * query-tag presets, …). Forwarded verbatim to SEA
   * `session_confs`. Unknown keys are rejected server-side.
   */
  sessionConf?: Record<string, string>
  /**
   * Maximum number of pooled HTTP connections per host. Routes
   * through the kernel's `HttpConfig::pool_max_idle_per_host`.
   * Tunes the underlying `reqwest` connection pool — higher values
   * reduce reconnect overhead when many statements run
   * concurrently against the same warehouse. `None` falls back to
   * the kernel default (100). Mirrors the Python connector's
   * `max_connections` kwarg on the SEA backend.
   *
   * Napi-rs serialises `u32` as JS `number`; values up to
   * `2^32 - 1` round-trip safely (any reasonable pool size fits).
   */
  maxConnections?: number
}
/**
 * Open a Databricks SQL session over PAT auth and return an opaque
 * `Connection` wrapping the kernel `Session`.
 *
 * The JS-visible name is `openSession` (napi-rs converts snake_case
 * to camelCase for free functions).
 */
export declare function openSession(options: ConnectionOptions): Promise<Connection>
/**
 * Per-statement options for `Connection.executeStatement`.
 * Mirrors the napi-rs-generated `ExecuteOptions` in
 * `napi/src/connection.rs`. Today carries:
 * - `statementConf` — per-statement Spark conf overlay merged on top
 *   of the session-level `sessionConf` at execute time. Map wins on
 *   key collisions.
 * - `queryTags` — JSON-encoded into `statementConf["query_tags"]`
 *   matching NodeJS Thrift's `serializeQueryTags` shape. Passing both
 *   `queryTags` and an explicit `statementConf["query_tags"]` raises
 *   `InvalidArgument`.
 */
export interface ExecuteOptions {
  statementConf?: Record<string, string>
  queryTags?: Record<string, string>
}
/**
 * A single Arrow IPC stream payload encoding one record batch (plus
 * the schema header so the JS-side reader is stateless).
 */
export interface ArrowBatch {
  ipcBytes: Buffer
}
/**
 * An Arrow IPC stream payload encoding just the result schema (no
 * record-batch messages). Returned by `Statement.schema()` or
 * `AsyncResultHandle.schema()`.
 */
export interface ArrowSchema {
  ipcBytes: Buffer
}
/**
 * Opaque async-statement handle returned by
 * `Connection.submitStatement(...)`. The kernel sent
 * `wait_timeout=0s`, so the server is still Pending/Running when
 * this handle is constructed; JS drives polling via `status()` or
 * blocks via `awaitResult()`. Drop-cancel during `awaitResult()`
 * is handled by the kernel's `AwaitResultCancelGuard`.
 */
export declare class AsyncStatement {
  /** Server-issued statement id. Cached at construction. */
  get statementId(): string
  /**
   * One-shot status check. Returns
   * `'Pending' | 'Running' | 'Succeeded' | 'Failed' | 'Cancelled' |
   *  'Closed' | 'Unknown'`. Returns `KernelError(InvalidStatementHandle)`
   * if the statement has been explicitly `close()`d.
   */
  status(): Promise<string>
  /**
   * Block until the server reaches a terminal state, then return an
   * `AsyncResultHandle` that wraps the materialised result stream.
   */
  awaitResult(): Promise<AsyncResultHandle>
  /** Server-side cancel. */
  cancel(): Promise<void>
  /** Explicit close. Idempotent. */
  close(): Promise<void>
}
/**
 * Opaque result-fetch handle returned by
 * `AsyncStatement.awaitResult()`. Wraps a kernel `ResultStream`.
 * No `cancel()` / `close()` — the parent `AsyncStatement` owns
 * server-side lifecycle.
 */
export declare class AsyncResultHandle {
  /** Server-issued statement id. Matches the parent `AsyncStatement`. */
  get statementId(): string
  /**
   * Pull the next batch of results. Returns `null` when the stream
   * is exhausted. Byte-identical IPC payload to the sync
   * `Statement.fetchNextBatch()` for the same query.
   */
  fetchNextBatch(): Promise<ArrowBatch | null>
  /** Result schema as a schema-only Arrow IPC payload. */
  schema(): Promise<ArrowSchema>
}
/**
 * Returns the native binding's crate version (`CARGO_PKG_VERSION`).
 *
 * Originally the round-1b smoke test; kept as a cheap "is the binding
 * loaded?" probe for the JS-side loader's structured diagnostics.
 */
export declare function version(): string
/**
 * Opaque connection handle wrapping a kernel `Session`.
 *
 * `inner` is `Arc<Mutex<Option<Session>>>` so:
 * - the Drop impl can clone the `Arc` and `.take()` the session on a
 *   background tokio task without holding `&mut self` (which Drop is
 *   forbidden from doing across an `await`),
 * - `executeStatement` can share immutable access to the session via
 *   the `Arc<SessionInner>` clones the kernel makes internally
 *   (`Session::statement()` only needs `&self`).
 */
export declare class Connection {
  /**
   * Execute a SQL statement and return a Statement handle that
   * streams batches via `fetchNextBatch()`.
   *
   * Catalog / schema / sessionConf are session-level (`openSession`).
   * `options` carries per-statement knobs: `statementConf`
   * (per-statement Spark conf overlay) and `queryTags` (serialised
   * into `statementConf["query_tags"]` matching NodeJS Thrift's
   * `serializeQueryTags` wire shape).
   */
  executeStatement(sql: string, options?: ExecuteOptions | undefined | null): Promise<Statement>
  /**
   * Submit a SQL statement asynchronously and return an
   * `AsyncStatement` handle. The kernel `Statement::submit()` sends
   * `wait_timeout=0s`, so the server returns immediately with a
   * statement_id while the query is still Pending/Running. Drive
   * polling via the returned handle.
   */
  submitStatement(sql: string, options?: ExecuteOptions | undefined | null): Promise<AsyncStatement>
  /**
   * Explicit close. Marks the connection wrapper as closed so
   * subsequent calls on this `Connection` return `InvalidArg`, then
   * schedules a fire-and-forget server-side close on the runtime.
   *
   * **Why fire-and-forget and not `Session::close().await`:** the
   * kernel's `Session::close(self).await` body holds a
   * `tracing::EnteredSpan` (a `!Send` type) across an `.await`, so
   * the future is not `Send`. napi-rs's `execute_tokio_future` glue
   * rejects non-`Send` futures, and `Handle::spawn` does too. The
   * kernel's `SessionInner::Drop` already spawns the
   * `delete_session` RPC on the same runtime handle the napi
   * binding captured, so dropping the value is functionally
   * equivalent — the difference is that JS callers can't observe a
   * `delete_session` failure from `close()`. Tracked as a kernel-
   * side follow-up (clone the span rather than entering it) in
   * Round 3 findings.
   */
  close(): Promise<void>
}
/**
 * Opaque executed-statement handle.
 *
 * `inner` is wrapped in `Arc<Mutex<Option<…>>>` so:
 * - `fetch_next_batch` can `await` `ResultStream::next_batch` which
 *   requires `&mut ExecutedStatement` (via `result_stream_mut`),
 * - `cancel` / `close` (which take `&self` on the kernel side via the
 *   `ExecutedStatementHandle` trait) can run concurrently with each
 *   other from a JS perspective without panicking,
 * - `Drop` can hand the inner handle off to a tokio task without
 *   touching `&mut self` across an `await`.
 */
export declare class Statement {
  /**
   * Pull the next batch of results. Returns `None` when the stream
   * is exhausted. The returned `ArrowBatch.ipcBytes` is a complete
   * Arrow IPC stream (schema header + 1 record-batch message)
   * suitable for handing to `apache-arrow`'s `RecordBatchReader`.
   */
  fetchNextBatch(): Promise<ArrowBatch | null>
  /**
   * Result schema as an Arrow IPC payload (schema header only, no
   * record-batch message). Available before any batches have been
   * fetched.
   */
  schema(): Promise<ArrowSchema>
  /** Server-side cancel. No-op if already finished. */
  cancel(): Promise<void>
  /**
   * Explicit close. Awaits the server-side close so the JS caller
   * can observe failures.
   */
  close(): Promise<void>
}
